### ISSUE TITLE
Create implementation-agnostic ADEPT documentation

### ISSUE THREAD

**Issue by JJTech0130** [Leseratte10/acsm-calibre-plugin#10]
It would be great if you could create some kind of spec for ADEPT so that different implementations can be made without reading all of the source code. I'm doing a lot of work for my rust implementation just trying to figure out all of what needs to be done.

**Comment by Leseratte10** [comment]
Interesting suggestion (and I agree that something like that might have been helpful when I created the plugin based on libgourou), but creating a complete documentation that's actually useful and contains all information needed to reimplement this would probably be a ton of work, with no direct benefit to me, so I don't think I'm going to be doing that. 

Though, if you have any specific issues with your own implementation or if you are stuck somewhere, like a particular error code from Adobe you can't get fixed, feel free to let me know and I'll see if I can help.

**Comment by JJTech0130** [comment]
Well, I'm trying to design my version in a more object oriented fashion. For now, I have a User object that is created with the sign in method, a username, and a password, and has a getLicenseKey function that will return the license key for the user. I haven't gotten much further 😄

**Comment by JJTech0130** [comment]
@Leseratte10 What is the auth key in the sign-in used for? Can I simply reuse the license key?

**Comment by Leseratte10** [comment]
I'm not sure what it's used for. Looking through the code it looks like it's not used for anything. Though, ADE does use two different keys for auth and license so I decided to do that, too. No idea if you could re-use the license key.

**Comment by Leseratte10** [comment]
As I currently don't plan writing an ADEPT documentation as requested in this issue, I'm going to close this issue as "wont fix" for now. If you have more questions while implementing your Rust version feel free to post them here regardless.
