### ISSUE TITLE
Installation impossible

### ISSUE THREAD

**Issue by baeuchle** [Leseratte10/acsm-calibre-plugin#102]
### Bug description

Trying to install calibre-plugin.zip both from the artifacts mentioned in https://github.com/Leseratte10/acsm-calibre-plugin/issues/100#issuecomment-2292909869 as well as from a self-bundled version at current master (checked out, ran .(bundle_calibre_plugin.sh). For both, tried to "install extension from file" in Calibre and navigated to the zip file.

Result is "invalid plugin" with the following traceback:

> calibre, version 7.6.0
> FEHLER: Unbehandelter Ausnahmefehler: <b>InvalidPlugin</b>:Initialisierung der Erweiterung Traceback (most recent call last):
>   File "/usr/lib/calibre/calibre/customize/ui.py", line 710, in initialize_plugin
>     p.initialize()
>   File "calibre_plugins.deacsm.__init__", line 232, in initialize
>     deacsmprefs = prefs.DeACSM_Prefs()
>                   ^^^^^^^^^^^^^^^^^^
> AttributeError: module 'calibre_plugins.deacsm.prefs' has no attribute 'DeACSM_Prefs'
>  fehlgeschlagen. Rückverfolgung:
> Traceback (most recent call last):
>   File "/usr/lib/calibre/calibre/customize/ui.py", line 710, in initialize_plugin
>     p.initialize()
>   File "calibre_plugins.deacsm.__init__", line 232, in initialize
>     deacsmprefs = prefs.DeACSM_Prefs()
>                   ^^^^^^^^^^^^^^^^^^
> AttributeError: module 'calibre_plugins.deacsm.prefs' has no attribute 'DeACSM_Prefs'
> 
> 
> calibre 7.6  embedded-python: False
> Linux-6.8.0-104036-tuxedo-x86_64-with-glibc2.39 Linux ('64bit', 'ELF')
> ('Linux', '6.8.0-104036-tuxedo', '#36tux1 SMP PREEMPT_DYNAMIC Mon Jul  1 17:42:27 UTC 2024')
> Python 3.12.3
> Interface language: de
> EXE path: /usr/bin/python3.12
> Successfully initialized third party plugins: DeDRM (10, 0, 3)
> Traceback (most recent call last):
>   File "/usr/lib/calibre/calibre/customize/ui.py", line 710, in initialize_plugin
>     p.initialize()
>   File "calibre_plugins.deacsm.__init__", line 232, in initialize
>     deacsmprefs = prefs.DeACSM_Prefs()
>                   ^^^^^^^^^^^^^^^^^^
> AttributeError: module 'calibre_plugins.deacsm.prefs' has no attribute 'DeACSM_Prefs'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/calibre/calibre/gui2/preferences/plugins.py", line 325, in add_plugin
>     plugin = add_plugin(path)
>              ^^^^^^^^^^^^^^^^
>   File "/usr/lib/calibre/calibre/customize/ui.py", line 520, in add_plugin
>     plugin = initialize_plugin(plugin, path_to_zip_file, PluginInstallationType.EXTERNAL)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/calibre/calibre/customize/ui.py", line 715, in initialize_plugin
>     raise InvalidPlugin((_('Initialization of plugin %s failed with traceback:')
> calibre.customize.InvalidPlugin: Initialisierung der Erweiterung Traceback (most recent call last):
>   File "/usr/lib/calibre/calibre/customize/ui.py", line 710, in initialize_plugin
>     p.initialize()
>   File "calibre_plugins.deacsm.__init__", line 232, in initialize
>     deacsmprefs = prefs.DeACSM_Prefs()
>                   ^^^^^^^^^^^^^^^^^^
> AttributeError: module 'calibre_plugins.deacsm.prefs' has no attribute 'DeACSM_Prefs'
>  fehlgeschlagen. Rückverfolgung:
> Traceback (most recent call last):
>   File "/usr/lib/calibre/calibre/customize/ui.py", line 710, in initialize_plugin
>     p.initialize()
>   File "calibre_plugins.deacsm.__init__", line 232, in initialize
>     deacsmprefs = prefs.DeACSM_Prefs()
>                   ^^^^^^^^^^^^^^^^^^
> AttributeError: module 'calibre_plugins.deacsm.prefs' has no attribute 'DeACSM_Prefs'

### Operating system

Linux

### Which version of Calibre are you running?

7.6.0

### Which version of the ACSM Input plugin are you running?

v0.0.16-47-g6c29c42

### Further information

Occured while trying to work around bug https://github.com/Leseratte10/acsm-calibre-plugin/issues/100

**Comment by Leseratte10** [comment]
This is part of the reason the new beta version still hasn't been published as a real release - there's some kind of issue updating from 0.0.16 to the newest beta. 

Try completely removing the plugin from Calibre, then restart Calibre twice (!), then try to re-install the beta, then it should work.

**Comment by baeuchle** [comment]
Ok now that is some serious black magic, but it works :) Good looking getting a handle on that und noch einen schönen abend aus Nordhessen.
