### ISSUE TITLE
"This book is locked by DRM" after adding

### ISSUE THREAD

**Issue by Powersource** [Leseratte10/acsm-calibre-plugin#12]
### Bug description

* Installed plugin
* Created anonymous ID thing
* Restarted calibre
* Imported the acsm file I got from my library, the book got added with the correct title and author, and I can find the .epub file in my file system
* Double-click it in calibre, it opens the book reader but shows me the below alert

![image](https://user-images.githubusercontent.com/1427063/147616643-1062b51f-b96f-44e9-811d-3c6421637701.png)

### Operating system

Linux

### Which version of Calibre are you running?

5.34

### Which version of the DeACSM plugin are you running?

?

**Comment by Leseratte10** [comment]
That's how it's intended to work. This plugin just creates the eBook file, it does not remove DRM. If you do want to remove DRM (which would be necessary to read books with an anonymous ID) you'll have to download and install the DeDRM plugin, just like with books from ADE. 

If you're using noDRM's fork, that should work out of the box without additional setup. If you're using Apprentice Harper's original version, you'll first need to extract the key from the DeACSM plugin and import it into the DeDRM plugin. 

If this still doesn't work even with the DeDRM plugin installed (you'll need to re-import the ACSM file after installing that plugin) please post a debug log.

**Comment by Powersource** [comment]
Ah thanks, I'll try that. Could probably clarify this in the readme (which I did read, maybe not thoroughly enough though).

**Comment by Leseratte10** [comment]
The readme already mentions in the Setup script that you'll need to export the key and import that into the DeDRM plugin for DRM removal when not using noDRM's fork:

> After you've activated the plugin, make a backup of the activation using the "Export account activation data". Then click "Export account encryption key" and import the resulting file into the DeDRM plugin for DRM removal. If you're using noDRM's fork of the DeDRM plugin, this step will happen automatically.

Or did you mean something else? How should that be clarified? Another sentence that Calibre can't read DRM-ed books?

**Comment by Powersource** [comment]
I was hoping that that step was optional and only applied if I was using one of those plugins. I think maybe it's clearer if there's an explicit: `How to use: 1. ... 2. ... 3. ...` right now it's more of a wall of text and it's unclear what exactly is important.

**Comment by Leseratte10** [comment]
It used to be an explicit list, but now that there are four different methods to create an authorization (displayed as a list), I didn't want to have a list in a list (that would also be confusing) and re-wrote the setup instructions as they are now.

**Comment by Leseratte10** [comment]
I'm going to close this issue as I assume installing the DeDRM plugin and importing the key fixed the issue, if there's still issues feel free to comment again or re-open.

**Comment by Powersource** [comment]
Yes it did solve it, thanks.

I think my confusion stems from that I thought what this plugin did was remove the DRM, when in fact it was sort of just the first layer of it.

**Comment by Leseratte10** [comment]
Great. 

Yeah, DRM removal is not what this plugin does. As that's not really 100% legal I'm not going to get involved with that. All this plugin does is take the weird ACSM download ticket file and turn it into a DRM-encrypted EPUB or PDF book.
