### ISSUE TITLE
False positive as Program:Win32/Uwamson.A!ml on Windows 11

### ISSUE THREAD

**Issue by JJTech0130** [Leseratte10/acsm-calibre-plugin#13]
Not sure if this is already resolved with https://github.com/Leseratte10/acsm-calibre-plugin/commit/964d4c06eb6c46354a3437fe7ba97763374b0a70, but when I updated the plugin through Calibre, Windows flagged and removed it as "Program:Win32/Uwamson.A!ml".

**Comment by Leseratte10** [comment]
That should be resolved with this commit, yeah. Will be included in the next release. I have no idea why Windows Defender flags that as malware, all that that binary does is decrypt some ADE data, as seen in the main.c in the "keyextract" folder.
