### ISSUE TITLE
fulfill.py doesn't accept any filename besides "URLLink.acsm"

### ISSUE THREAD

**Issue by fturco** [Leseratte10/acsm-calibre-plugin#18]
### Bug description

I use fulfill.py directly to get books from .acsm files, without using Calibre. I noticed that fulfill.py only accepts .acsm files named "URLLink.acsm", and rejects any other filename. Is there a reason for this behavior? I think fulfill.py would be easier to use if it just accepted any .acsm filename.

### Operating system

Linux

### Which version of Calibre are you running?

none

### Which version of the DeACSM plugin are you running?

0.0.15

**Comment by Leseratte10** [comment]
No real reason - the "fulfill.py" script is very old and I basically only used / needed it during development when I has the Python implementation of the Adobe stuff implemented but didn't yet have all the Calibre plugin hooks. 

Should be fairly easy to add some kind of parameter to use a custom file name. I'm going to add that with the next version.
