### ISSUE TITLE
Document E_AUTH_USER_AUTH

### ISSUE THREAD

**Issue by JJTech0130** [Leseratte10/acsm-calibre-plugin#29]
I just thought it might be useful to document (in the error codes wiki) the `E_AUTH_USER_AUTH` error code: something along the lines of:
> This error occurs if the XML signature is invalid and can't be parsed properly. This either means something went wrong when generating the signature, or it's an Adobe server issue.
>
> If this happens with the Calibre plugin, please open a bug report.

**Comment by Leseratte10** [comment]
Done, thanks.
