### ISSUE TITLE
Suggestion: Make an Icon in the Main Menu

### ISSUE THREAD

**Issue by p1nkyy** [Leseratte10/acsm-calibre-plugin#32]
Hi, is it possible to have an icon in the Main Menu like Kindle Unpack does? This is for other feature like returning books, authorizing ADE, etc. Thanks for considering this!

**Comment by Leseratte10** [comment]
This has already been suggested before on the Mobileread thread. This is possible but somewhat tricky. Usually, FileTypePlugins like mine are not able to have menu icons, so to get that to work I'd need to bundle two plugins in one ZIP - the FileTypePlugin that does the actual work and a GUI plugin that can have buttons and can then trigger the FileTypePlugin to do stuff. 

It's on my to-do list but I haven't had time to look into that yet.

**Comment by p1nkyy** [comment]
Thanks for even considering this!

**Comment by Leseratte10** [comment]
The newest commit of this plugin now has a rudimentary GUI button in the main toolbar that can A) open the settings dialog or B) directly open the loaned book list. 

Note that that update also changed around a bunch of internals and is not well tested, so if you'd like to test that, you NEED to make a backup of your authorization before installing that beta. 

https://github.com/Leseratte10/acsm-calibre-plugin/suites/8142083031/artifacts/353071557

**Comment by p1nkyy** [comment]
Thanks! Didn't realize this wiped all titles in loaned books list. Can they be restored using the backup?

**Comment by Leseratte10** [comment]
Hm. I didn't change how the loaned book list worked with this update. Interesting that that would be wiped, I'll have to test that again. 
No, the authorization backup is just for the authorization, it doesn't include the loaned book list.

**Comment by p1nkyy** [comment]
No, the book return issue was using the older beta, then I updated to this one and found the loaned book is empty. I have since processed more books and they show up fine. I think if I re-processed the older ACSMs, they should re-appear so it's not a big deal, just thought it's worth mentioning.

**Comment by Leseratte10** [comment]
Definitely worth mentioning, this update is supposed to migrate all data including the loan list. Maybe that migration doesn't properly work on Windows, I've only tested that on Linux so far.
