### ISSUE TITLE
Is it possible to open acsm URL link and download PDF directly using this plugin?

### ISSUE THREAD

**Issue by biozzl** [Leseratte10/acsm-calibre-plugin#33]
Is it possible to open acsm URL link and download PDF directly using this plugin?

**Comment by Leseratte10** [comment]
You mean entering the URL into Calibre and having Calibre download the ACSM and then the book? No, that's not supported; you first need to download the ACSM file through a browser or something, and then add the file as if it was a book. 

Is there a particular use-case you would need that for?

**Comment by biozzl** [comment]
> You mean entering the URL into Calibre and having Calibre download the ACSM and then the book? No, that's not supported; you first need to download the ACSM file through a browser or something, and then add the file as if it was a book.
> 
> Is there a particular use-case you would need that for?

Thank you for the reply, I used to download books from archive.org, it seems they only provide acsm URL link for the downloading.
I feel it will be good if this function get supported in order to get rid of ADE

**Comment by Leseratte10** [comment]
I fail to see why this requires any changes to the plugin, and I've downloaded multiple books from archive.org with this plugin before. 

If you're on the Archive.org website, loaning a book, and they give you a link to an ACSM file, you just click on it and download the ACSM file just like you would do with any other book. You can even configure Calibre to auto-add all ACSM files your browser places into the "Downloads" folder. 

Why is there a need to be able to copy-paste a download link into Calibre? I don't think ADE supports that either.

**Comment by biozzl** [comment]
> 

Can guide me how to download via Calibre？
What I get is a "URLLink.acsm" which I failed to open in Calibre，but only works from ADE to download the PDF
 from “URLLink.acsm” then I added the PDF into Calibre manually.
My intension is get rid of using ADE but using Calibre and plugin instead

One example of "URLLink.acsm" is giving here [URLLink.zip](https://github.com/Leseratte10/acsm-calibre-plugin/files/9567064/URLLink.zip)

**Comment by biozzl** [comment]
> I fail to see why this requires any changes to the plugin, and I've downloaded multiple books from archive.org with this plugin before.
> 
> If you're on the Archive.org website, loaning a book, and they give you a link to an ACSM file, you just click on it and download the ACSM file just like you would do with any other book. You can even configure Calibre to auto-add all ACSM files your browser places into the "Downloads" folder.
> 
> Why is there a need to be able to copy-paste a download link into Calibre? I don't think ADE supports that either.

Can guide me how to download via Calibre？
What I get is a "URLLink.acsm" which I failed to open in Calibre，but only works from ADE to download the PDF
from “URLLink.acsm” then I added the PDF into Calibre manually.
My intension is get rid of using ADE but using Calibre and plugin instead

One example of "URLLink.acsm" is giving here 
[URLLink.zip](https://github.com/Leseratte10/acsm-calibre-plugin/files/9567076/URLLink.zip)

**Comment by Leseratte10** [comment]
You take that URLLink.acsm file and add it into Calibre. Either by Drag-and-Drop, or by clicking "Add books" in the Calibre menu bar then opening the file. 

If that doesn't work or fails to open, you will need to post a debug log of the import attempt - start Calibre in debug mode (Preferences -> Restart in debug mode), then add the ACSM file, then close Calibre, then post the log file that opens afterwards.

**Comment by p1nkyy** [comment]
> 

Literally explained in the Readme.md in the front, maybe you're new to de-DRM-ing stuff I guess, but your question is pretty basic.

**Comment by tjwalch** [comment]
No it isn't. I can confirm that with Calibre version 6.4.0 and plugin version 0.0.16 opening a .ascm file with "Add books" or drag-and-drop doesn't download the book, it just adds the ascm-file as is.

**Comment by Leseratte10** [comment]
Closing this issue as there's been no response for a while. 

In general, this plugin obviously supports importing a downloaded URLLink.acsm file into Calibre (either with drag-and-drop, with the "Add books" dialog or with the auto add function), which is what I believe has been asked here. The plugin does not support downloading ACSM files from a HTTP URL (which is how I first misinterpreted this question / request). 

If there's more issues with the plugin not turning an ACSM file into a book, please open a new bug report and attach a debug log.
