### ISSUE TITLE
How can I import to Calibre?

### ISSUE THREAD

**Issue by balz666** [Leseratte10/acsm-calibre-plugin#39]
The instructions say to import to Calibre, but there is no zip file in the folder from which I can load the plugin.

How is it done?

Sorry if it looks like a stupid question, but I just don't see how to integrate the plugin to Calibre. Any help would be greatly appreciated.

**Comment by Leseratte10** [comment]
Not sure if this is already solved, but you need to download the plugin ZIP file (either from the Releases page for the latest release, or from the Actions page for the latest beta) and import the downloaded ZIP file itself, not any of its contents.

**Comment by balz666** [comment]
Yeah, that was stupid of me! I finally installed it directly from Calibre and now it works. 

Thanks!
