### ISSUE TITLE
Calibre loads the file but plugin does not find the book

### ISSUE THREAD

**Issue by datadecoded** [Leseratte10/acsm-calibre-plugin#41]
### Bug description

Hello and thanks for all of your hard work with this plugin! 

I'm using the plugin on a Linux machine running PopOS and have deDRM installed as well. I have some books in ASCM format and have added those to Calibre and they open just fine using deDRM. Other ASCM files when added to Calibre remain as ASCM files instead of being converted to epub format. Should I change the ADE version? Thanks again! 

### Operating system

Linux

### Which version of Calibre are you running?

6.8

### Which version of the ACSM Input plugin are you running?

0.0.16

**Comment by Leseratte10** [comment]
It's unlikely that changing the ADE version in the settings is going to help. If some files stay as ACSM and don't turn into an EPUB or PDF then some error occurred during the import. 

Try starting Calibre in debug mode (right-click the "Preferences" button then choose "Restart in debug mode"), then import the ACSM again and close Calibre and a log file should show up which you can add to this bug report.

**Comment by Leseratte10** [comment]
What do you mean with that? It doesn't open the debug log after closing Calibre?

You can also try running `calibre-debug -g` from a command line, that should print the debug log right there.

**Comment by Leseratte10** [comment]
Okay, the main error message (that comes from the server) is this: 

"E_ADEPT_REQUEST_EXPIRED: 2022-11-14T00:00:56-05:00 (1668402056000) is before 2022-11-16T17:59:43-05:00 (1668639583125)"

Looks like the ACSM expired on November 14th but you tried to use it in Calibre on November 16th. Try re-downloading the ACSM file from the source and see if it works then.
