### ISSUE TITLE
DeACSM does not turn ACSM into epub

### ISSUE THREAD

**Issue by johunb** [Leseratte10/acsm-calibre-plugin#43]
### Bug description

I have bought an ebook with format epub and DRM.

Windows 10: I have downloaded the ACSM file and imported it in Adobe Digital Edition v2.0.1 and got the epub with DRM. The I used epubee to make it DRM free. It worked fine.

Linux: I have downloaded the ASCM file. I have installed Calibre v6.9.0 and two configured Plug-ins: DeACSM v0.0.16, DeDRM v10.0.3. Then I imported the ACSM file into Calibre but DeACSM does not turn ACSM into epub. The I imported the epub with DRM (the one I got from Windows) and wanted DeDRM to remove the DRM. But it did not work. Calibre viewer told me, that the eBook has DRM.
Then I have loaned an ebook from a Library. I have downloaded the ACSM file and imported the ACSM file into Calibre. This time the two Plug-ins worked correctly. DeACSM turned ACSM into epub and DeDRM removed the DRM successfully.

Any ideas? Thank you in advance!

### Operating system

Linux

### Which version of Calibre are you running?

6.9.0

### Which version of the ACSM Input plugin are you running?

v.0.0.16

**Comment by JJTech0130** [comment]
This is just a guess, but if you used Adobe Digital Editions to remove the DRM first, the ASCM file would be tied to that account, and if you weren't using the same account (or were using an anonymous account) on Linux, it wouldn't be able to remove the DRM. You'd either need to sign in with the same account or get the ASCM regenerated.

**Comment by Leseratte10** [comment]
That's most likely the reason. 

Do you have ADE 2 and my plugin connected to the same AdobeID, or different ones / anonymous ones? The ACSM you imported into ADE will be linked to the AdobeID your ADE is using, so if you're using a different authorization in Calibre you can't reimport it again. 

Take a look at the error messages printed by Calibre in debug mode - start it with `calibre-debug -g` or by right-clicking the "Preferences" button then select "Restart in debug mode".

**Comment by johunb** [comment]
Tank you very much for your fast reply.

I think you are right. I installed Adobe Digital Edition under Windows as an anonymous user but installed Calibre and the two Plug-ins not as an anonymous user. I tried to install Adobe Digital Edition under Windows with the same credentials like under Linux, but I got an error: E_LIC_ALREDAY_FULLFILLED_BY_ANOTHER_USER

**Comment by Leseratte10** [comment]
That's the issue, yeah. Upon first opening an ACSM file, this file will be permanently linked to the user account, so, your anonymous Windows ADE authorization. Getting that anonymous authorization moved to Linux Calibre is going to be tricky. 

The error `E_LIC_ALREDAY_FULLFILLED_BY_ANOTHER_USER` means exactly that: You're opening an ACSM that already belongs to another account.

**Comment by Leseratte10** [comment]
No. Being able to do that ("cancelling" that connection) would mean that you could share the ACSM with other users and have them all access the book. 

What you can do is convert the anonymous user to a *new* AdobeID account with an email - but only if that AdobeID account has just been created and has never been added to either ADE or my plugin at all.

But it'd probably be easier to install Calibre on your Windows machine, remove the DRM from that one book on Windows, and then forget about ADE with its anonymous authorization and only use my plugin with a proper user account in the future.

**Comment by johunb** [comment]
OK, thank you very much. I'll do so!

**Comment by Leseratte10** [comment]
`E_LIC_ALREDAY_FULLFILLED_BY_ANOTHER_USER` is not an error in my plugin, so I'm going to close this issue. 

If you have more problems with new- unused ACSM files feel free to open another bug report.
