### ISSUE TITLE
How to setup via terminal for Calibre Content Server

### ISSUE THREAD

**Issue by hugoromo** [Leseratte10/acsm-calibre-plugin#50]
How can I setup the plug for this matter?

**Comment by Leseratte10** [comment]
The plugin can only be configured through the GUI, it doesn't have a command line interface for configuration. 

If you want to run Calibre completely without GUI it's probably easiest to install it somewhere where you have a GUI, configure the plugin, then copy over all the config.

**Comment by Leseratte10** [comment]
No response, I'm assuming this is solved. If there's still issues running the plugin on a content server with a working config, please comment again.
