### ISSUE TITLE
pdftohtml conversion fails during import 

### ISSUE THREAD

**Issue by klreeher** [Leseratte10/acsm-calibre-plugin#54]
### Bug description

This is the first time I'm using the ACSM-Calibre-Plugin, but I was able to add the test library books successfully. 

System OS: Ubuntu 22.10

I was attempting to import a book that was loaned via archive.org, which is an encrypted adobe pdf, `.acsm`.

Attempt no. 1:

- I added the ACSM-Calibre-Plugin to my calibre install, which had a pre-existing noDRM de-drm plugin installed.
   - i also happened to turn the verbose logging on 
- I restarted Calibre, then authorized the ACSM plugin with my adobe id. (the same adobe id that i can open the pdf in adobe editions with)
- I exported the key to file.
- In the noDRM de-drm plugin, I clicked on Adobe Digital Editions Ebooks, then clicked the green + icon. It added a UUID to the list. 
![Screenshot from 2023-06-15 10-02-20](https://github.com/Leseratte10/acsm-calibre-plugin/assets/1613107/362779bb-6a6c-41df-810e-3229b8a8bcd3)
![Screenshot from 2023-06-15 10-02-39](https://github.com/Leseratte10/acsm-calibre-plugin/assets/1613107/a404b9f0-ab69-4de0-90e8-36383b10d634)

- I then attempted to drag and drop the .acsm file into calibre. 
- it showed the processing bar, but eventually failed. 
[import_fails.log](https://github.com/Leseratte10/acsm-calibre-plugin/files/11759965/import_fails.log)
- in my main calibre library, it shows the acsm file 
![image](https://github.com/Leseratte10/acsm-calibre-plugin/assets/1613107/e4cad08e-5d5e-459e-b6cb-d281f6737830)
- if i open the ACSM plugin's configuration menu, I do see my book listed as currently on loan -- however there are always two entries, even if I have only imported the book once. 
![image](https://github.com/Leseratte10/acsm-calibre-plugin/assets/1613107/a60ec325-cb44-4be8-9e3a-591198ad4090)

Other Attempts:
I tried the same general process several times but with the following changes:

- different ADE versions in the ACSM plugin config
- importing via add new book button vs drag and drop vs automatic import from local folder
- exporting the key explicitly to file and importing into the noDRM de-drm plugin rather than the Plus icon. 

no difference, and the logs still showed the ValueError exception:
> ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)

### Operating system

Linux

### Which version of Calibre are you running?

6.3.0

### Which version of the ACSM Input plugin are you running?

v0.0.16

### Import type

Clicking the 'Add books' button in the menu bar, Dragging-and-Dropping the ACSM file into the Calibre window, Using an auto-add folder (Preferences -> Adding books -> Automatic adding)

### Further information

Can also provide ACSM file used if desired.

**Comment by Leseratte10** [comment]
Interesting. The error "decoding with 'hex' codec failed" came up in older versions of the DeDRM plugin, but I assumed it would have been fixed by now. 

Did you delete the existing key(s) from the DeDRM plugin prior to importing the DER file? If not, can you test if that works?

If that still fails, you'll probably have to open a bug report in noDRM's repository because this sounds like a bug with DRM removal, not with my plugin.

**Comment by Leseratte10** [comment]
No response, assuming this issue is now fixed. If there's still issues feel free to re-open.
