### ISSUE TITLE
DeACSM and Windows

### ISSUE THREAD

**Issue by johunb** [Leseratte10/acsm-calibre-plugin#6]
Linux: DeACSM Version 0.0.10 works without errors. Adobe Digital Edition is not necessary any more.  acsm-files can be opened directly in Calibre and epubs get decrypted automatically using DeDRM 7.2.1. Very fine!

Windows: I have installed Calibre and the plugins DeACSM and DeDRM. Same configuration like Linux. But if I want to open acsm-file directly in Calibre it claims missing Adobe Digital Edition.

So, does DeACSM only work in Linux or is there a bug?

Thank you!

**Comment by Leseratte10** [comment]
The bugfix for this is now included in v0.0.11, so I'm closing this issue. If this occurs again, feel free to comment here again (or open a new issue).
