### ISSUE TITLE
Calibre crash upon linking ADE account

### ISSUE THREAD

**Issue by syamaka** [Leseratte10/acsm-calibre-plugin#62]
### Bug description

When trying to link ADE account (with any method), Calibre crashes and I get "wait/force quit" message. Tried almost all previous versions of ACSM plugin, and got the same issue.
I'm running Calibre v. 6.23 on Ubuntu 22.04.2 LTS. 

### Operating system

Linux

### Which version of Calibre are you running?

6.23

### Which version of the ACSM Input plugin are you running?

v0.0.16

**Comment by Leseratte10** [comment]
Interesting, I've never heard of that happening. 

Can you try running Calibre in debug mode (open a terminal and run `calibre-debug -g`) and post the log that appears when it crashes?

**Comment by syamaka** [comment]
This is all I get after running Calibre in debug mode (using Calibre UI; there's no log file created when I run it through command line as you suggested.):

`Using calibre Qt style: True
calibre Debug log
calibre 6.23  embedded-python: True
Linux-5.19.0-41-generic-x86_64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '5.19.0-41-generic', '#42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2')
Python 3.10.1
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 9)
calibre 6.23  embedded-python: True
Linux-5.19.0-41-generic-x86_64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '5.19.0-41-generic', '#42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2')
Python 3.10.1
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 9)
QPA platform: wayland
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 102.04823529411765 x 102.66947368421053
[0.00] Starting up...
[0.01] Showing splash screen...
[0.15] splash screen shown
[0.15] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
[1.23] main UI initialized...
[1.23] Hiding splash screen
Starting QuickView`

**Comment by syamaka** [comment]
This is all I get after running Calibre in debug mode (using Calibre UI; there's no log file created when I run it through command line as you suggested):

``Using calibre Qt style: True
calibre Debug log
calibre 6.23  embedded-python: True
Linux-5.19.0-41-generic-x86_64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '5.19.0-41-generic', '#42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2')
Python 3.10.1
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 9)
calibre 6.23  embedded-python: True
Linux-5.19.0-41-generic-x86_64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '5.19.0-41-generic', '#42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2')
Python 3.10.1
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 9)
QPA platform: wayland
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 102.04823529411765 x 102.66947368421053
[0.00] Starting up...
[0.01] Showing splash screen...
[0.15] splash screen shown
[0.15] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
[1.23] main UI initialized...
[1.23] Hiding splash screen
Starting QuickView``

**Comment by syamaka** [comment]
This is all I get after running Calibre in debug mode (using Calibre UI; there's no log file created when I run it through command line as you suggested):

``Using calibre Qt style: True
calibre Debug log
calibre 6.23  embedded-python: True
Linux-5.19.0-41-generic-x86_64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '5.19.0-41-generic', '#42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2')
Python 3.10.1
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 9)
calibre 6.23  embedded-python: True
Linux-5.19.0-41-generic-x86_64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '5.19.0-41-generic', '#42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2')
Python 3.10.1
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 9)
QPA platform: wayland
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 102.04823529411765 x 102.66947368421053
[0.00] Starting up...
[0.01] Showing splash screen...
[0.15] splash screen shown
[0.15] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
[1.23] main UI initialized...
[1.23] Hiding splash screen
Starting QuickView``

**Comment by Leseratte10** [comment]
So if you're saying that this is from Calibre's own "run in debug mode" thing, then this is probably a log just from Calibre starting, not from you trying to link your ADE account, right? Because when linking an account it'd crash and could no longer display the log?

When you run `calibre-debug -g` on the command line you should get the same stuff you posted here printed on the command line. And hopefully some more logs from my plugin during authorization. You can then just copy-paste it from the terminal.

**Comment by syamaka** [comment]
> So if you're saying that this is from Calibre's own "run in debug mode" thing, then this is probably a log just from Calibre starting, not from you trying to link your ADE account, right? Because when linking an account it'd crash and could no longer display the log?

That's all I got in the log file saved in tmp folder. And I guess yes, when linking an account it'd crash and there's no data after that point in the log file.

> When you run calibre-debug -g on the command line you should get the same stuff you posted here printed on the command line. And hopefully some more logs from my plugin during authorization. You can then just copy-paste it from the terminal.

Same here; no more data:

`calibre 6.24  embedded-python: True
Linux-5.19.0-41-generic-x86_64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '5.19.0-41-generic', '#42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2')
Python 3.10.1
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 9)
QPA platform: wayland
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 102.04823529411765 x 102.66947368421053
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.52] splash screen shown
[0.52] Initializing db...
[0.68] db initialized
[0.68] Constructing main UI...
[2.72] main UI initialized...
[2.72] Hiding splash screen
Starting QuickView
[3.14] splash screen hidden
[3.20] Started up in 3.20 seconds with 2 books
Killed
`
p.s: Upgraded Calibre to latest version; still facing the issue.

**Comment by Leseratte10** [comment]
Hm. "Killed" ...

There must be some reason why Calibre gets killed. When you run `dmesg -wT` as root in a terminal while Calibre crashes, does that display something that looks interesting?

Is this a new or new-ish installation of Calibre (and thus could be a generic Calibre issue) or have you been using Calibre successfully in the past without my plugin?

Where exactly does it crash? You can successfully see the settings window where it says "Not authorized for any ADE ID", and as soon as you click "Create anonymous authorization" it crashes and you don't see the warning dialog ("You are about to create ...")?

**Comment by Leseratte10** [comment]
No more response, assuming that the issue is no longer relevant. If it is, please re-open and answer the questions above.

**Comment by cartoonnerie** [comment]
I have the same symptoms on ubuntu 25.10 and calibre 8.8

Here are the logs through strace
```
ppoll([{fd=5, events=POLLIN}, {fd=8, events=POLLIN}, {fd=14, events=POLLIN}, {fd=26, events=POLLIN}, {fd=37, events=POLLIN}], 5, {tv_sec=0, tv_nsec=366000000}, NULL, 8) = 1 ([{fd=5, revents=POLLIN}], left {tv_sec=0, tv_nsec=303057298})
read(5, "\1\0\0\0\0\0\0\0", 8)          = 8
clock_gettime(CLOCK_MONOTONIC, {tv_sec=751625, tv_nsec=698186974}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=751625, tv_nsec=698242777}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=751625, tv_nsec=698291108}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=751625, tv_nsec=698333292}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=751625, tv_nsec=698375686}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=751625, tv_nsec=698417312}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=751625, tv_nsec=698457262}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=751625, tv_nsec=698500144}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=751625, tv_nsec=698542748}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=751625, tv_nsec=698585561}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=751625, tv_nsec=698621460}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=751625, tv_nsec=698660990}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=751625, tv_nsec=698696260}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=751625, tv_nsec=698734534}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=751625, tv_nsec=698770293}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=751625, tv_nsec=698808356}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=751625, tv_nsec=698845931}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=751625, tv_nsec=698883297}) = 0
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
futex(0x3358f3c, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x3358ef0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x3227888, FUTEX_WAKE_PRIVATE, 1) = 1
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
getpid()                                = 1939181
getpid()                                = 1939181
getpid()                                = 1939181
getpid()                                = 1939181
getpid()                                = 1939181
getpid()                                = 1939181
getpid()                                = 1939181
getpid()                                = 1939181
getpid()                                = 1939181
getpid()                                = 1939181
openat(AT_FDCWD, "/usr/lib/ssl/cert.pem", O_RDONLY) = 39
fstat(39, {st_mode=S_IFREG|0644, st_size=224449, ...}) = 0
read(39, "-----BEGIN CERTIFICATE-----\nMIIH"..., 4096) = 4096
read(39, "8B1\nRXxlDPiyN8+sD8+Nb/kZ94/sHvJw"..., 4096) = 4096
...many lines for certificates


read(39, "", 4096)                      = 0
close(39)                               = 0
newfstatat(AT_FDCWD, "/etc/nsswitch.conf", {st_mode=S_IFREG|0644, st_size=605, ...}, 0) = 0
newfstatat(AT_FDCWD, "/etc/resolv.conf", {st_mode=S_IFREG|0644, st_size=922, ...}, 0) = 0
openat(AT_FDCWD, "/etc/hosts", O_RDONLY|O_CLOEXEC) = 39
fstat(39, {st_mode=S_IFREG|0644, st_size=255, ...}) = 0
lseek(39, 0, SEEK_SET)                  = 0
read(39, "127.0.0.1 localhost\n127.0.1.1 al"..., 4096) = 255
read(39, "", 4096)                      = 0
close(39)                               = 0
rt_sigprocmask(SIG_BLOCK, [HUP USR1 USR2 PIPE ALRM CHLD TSTP URG VTALRM PROF WINCH IO], [], 8) = 0
openat(AT_FDCWD, "/run/systemd/machines/adeactivate.adobe.com", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=751625, tv_nsec=708727570}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=751625, tv_nsec=708765215}) = 0
socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 39
setsockopt(39, SOL_IP, IP_RECVERR, [1], 4) = 0
connect(39, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.53")}, 16) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1775649888, tv_nsec=511282074}) = 0
poll([{fd=39, events=POLLOUT}], 1, 0)   = 1 ([{fd=39, revents=POLLOUT}])
sendmmsg(39, [{msg_hdr={msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="0\36\1 \0\1\0\0\0\0\0\1\vadeactivate\5adobe\3c"..., iov_len=50}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, msg_len=50}, {msg_hdr={msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\210\253\1 \0\1\0\0\0\0\0\1\vadeactivate\5adobe\3c"..., iov_len=50}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, msg_len=50}], 2, MSG_NOSIGNAL) = 2
poll([{fd=39, events=POLLIN}], 1, 5000) = 1 ([{fd=39, revents=POLLIN}])
ioctl(39, FIONREAD, [183])              = 0
recvfrom(39, "0\36\201\200\0\1\0\2\0\1\0\1\vadeactivate\5adobe\3c"..., 2048, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.53")}, [28 => 16]) = 183
clock_gettime(CLOCK_REALTIME, {tv_sec=1775649888, tv_nsec=511742192}) = 0
poll([{fd=39, events=POLLIN}], 1, 4999) = 1 ([{fd=39, revents=POLLIN}])
ioctl(39, FIONREAD, [167])              = 0
recvfrom(39, "\210\253\201\200\0\1\0\1\0\1\0\1\vadeactivate\5adobe\3c"..., 65536, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.53")}, [28 => 16]) = 167
close(39)                               = 0
socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_TCP) = 39
connect(39, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("152.70.143.57")}, 16) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
connect(39, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("152.70.143.57")}, 16) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
connect(39, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("152.70.143.57")}, 16) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
connect(39, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("152.70.143.57")}, 16) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
connect(39, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("152.70.143.57")}, 16) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
connect(39, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("152.70.143.57")}, 16) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
connect(39, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("152.70.143.57")}, 16) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
connect(39, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("152.70.143.57")}, 16) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
connect(39, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("152.70.143.57")}, 16) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
connect(39, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("152.70.143.57")}, 16) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
connect(39, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("152.70.143.57")}, 16) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
connect(39, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("152.70.143.57")}, 16) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
connect(39, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("152.70.143.57")}, 16) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
connect(39, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("152.70.143.57")}, 16) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
connect(39, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("152.70.143.57")}, 16) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
connect(39, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("152.70.143.57")}, 16) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
connect(39, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("152.70.143.57")}, 16) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
connect(39, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("152.70.143.57")}, 16) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
connect(39, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("152.70.143.57")}, 16) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
connect(39, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("152.70.143.57")}, 16) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
connect(39, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("152.70.143.57")}, 16) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
connect(39, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("152.70.143.57")}, 16) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
connect(39, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("152.70.143.57")}, 16

```
Nothing interesting through calibre-debug nor dmesg -wT

It is a newish install but I had a previous library and maybe some config left. No other bug to report in calibre.

I tried to set my own account and it crashes right on this click. If I try the anonymous setup, it crashes right after selecting ADE version.

I know it is much later but I tried to document the issue and I am willing to keep answering
