### ISSUE TITLE
Deauthorize

### ISSUE THREAD

**Issue by mtissington** [Leseratte10/acsm-calibre-plugin#74]
### Bug description

I have authorized calibre .. but how do I DEauthorize calibre (so I can authorize using my id)
I tried to delete and re install the plugin but it just remembers the last authorization.

### Operating system

MacOS

### Which version of Calibre are you running?

7.1.0

### Which version of the ACSM Input plugin are you running?

v0.0.16

**Comment by Leseratte10** [comment]
Not sure if this was closed on accident or not, but if someone else reads this, just open the plugin settings, press CTRL+SHIFT+D, then follow the instructions.

**Comment by johnjaylward** [comment]
Yeah, that was not obvious at all. Can we get a button or something in the preferences for this?
