### ISSUE TITLE
c't Magazin not properly deacsmed

### ISSUE THREAD

**Issue by Dondo11** [Leseratte10/acsm-calibre-plugin#90]
### Bug description

As of issue 09/2024, c't Magazin cannot be properly deacsmed any longer.  The resulting pdf shows only advertisement pages, but all content is apparently present since the pdf is repairable using online repair services.  No obvious hitches in de Calibre debug log.

### Operating system

MacOS

### Which version of Calibre are you running?

7.7

### Which version of the ACSM Input plugin are you running?

v0.0.16

### Import type

Dragging-and-Dropping the ACSM file into the Calibre window

### Further information

[deACSM-ct.txt](https://github.com/Leseratte10/acsm-calibre-plugin/files/15374319/deACSM-ct.txt)

**Comment by Leseratte10** [comment]
If you take the PDF file from the ACSM plugin without repairing it with online tools and without removing DRM, does it render correctly in ADE or does it still only show the ads?

This sounds more like the source PDF used by the distributor is already corrupted in a way and is unlikely to be a bug in the plugin. I will take a closer look when I have time, though.

**Comment by Dondo11** [comment]
I'm sorry I have no answer to that because I don't use ADE at all.  I'm a user of Onleihe Verbund (which you may have heard of) via my local library.  Their app includes a rendering facility, and there the PDF displays correctly.

**Comment by Leseratte10** [comment]
Ah, it's from the Onleihe. I've reserved the c't 9/24 in my local Onleihe and will test it myself tomorrow when I get access.

**Comment by Dondo11** [comment]
Thanks a lot for taking the trouble!  Could provide an unrepaired copy of the magazine if necessary...

I also think its a structural glitch introduced by the publisher since c't is the only magazine/epaper I read where this happens.

**Comment by Leseratte10** [comment]
Can't reproduce the issue. I downloaded c't 09/2024 from my Onleihe and it opens just fine on Linux in Evince, so whatever the issue is in your case, I don't think it's going to be something that's caused by my plugin, or even something that can be fixed by my plugin.

**Comment by Dondo11** [comment]
Thanks once again for taking the time to reproduce this.  And I apologise for the ambiguity in the issue title:  I didn’t mean to imply that the plugin was the cause of this phenomenon as indeed the Calibre debug doesn’t show any anomalies.

So…  Looks like this is a macOS-specific glitch.  I suppose that comparing the PDF created on LInux with the one on macOS would reveal much if anything at all.  It‘s still interesting that other e-papers are not affected.

**Comment by Dondo11** [comment]
> … opens just fine on Linux in Evince …

Yes, indeed.  Just verified that the PDF from Calibre/deacsm created on macOS opens just fine in a Linux guest running under UTMapp without any repairs.  Looks like something's wrong in Apple's PDF-Preview core.  Bummer…
