### ISSUE TITLE
Can't process ACSM from CL

### ISSUE THREAD

**Issue by p1nkyy** [Leseratte10/acsm-calibre-plugin#91]
### Bug description

Hello, I can't seem to process ACSM from Cloud Library.

Here's the log:

[CL error.txt](https://github.com/Leseratte10/acsm-calibre-plugin/files/15390864/CL.error.txt)

### Operating system

Windows

### Which version of Calibre are you running?

7.10

### Which version of the ACSM Input plugin are you running?

v0.0.10

### Import type

Dragging-and-Dropping the ACSM file into the Calibre window, Using an auto-add folder (Preferences -> Adding books -> Automatic adding)

**Comment by Leseratte10** [comment]
Looks like a generic internet issue. Maybe your internet went out for a moment, or CloudLibrary had temporary issues. Can you try again and see if the issue is gone?

**Comment by p1nkyy** [comment]
Hi, yesterday I tried different title, no luck. Today I tried again, also no luck. Strangely ACSMs from other provider works.

**Comment by Leseratte10** [comment]
Hm. 

Can you try if it works with the "Notify ACS server after successful fulfillment" setting disabled?
If it doesn't, would you mind sending me an unused ACSM from that library to s4-tmp-fl7634x2wprw-github-acsm-91@leseratte10.de so I can try to reproduce it on my machine?

The logfile pretty clearly shows `socket.gaierror: [Errno 11001] getaddrinfo failed` which means the plugin was unable to do a DNS resolve for some domain ... though I agree it's unlikely that the library would have an outage like that, and all the domains I can see in the log resolve properly for me. 

Do you have any kind of DNS-based adblocker like PiHole or something in your network that might be interfering with the connection?

**Comment by p1nkyy** [comment]
Yes finally works. I don't have DNS based adblocker but my ISP do impose traffic filtering using DNS (that we can't get around) but previously there was no problem processing ACSM from CL. E-mail sent.
