### ISSUE TITLE
Can't process ACSM

### ISSUE THREAD

**Issue by p1nkyy** [Leseratte10/acsm-calibre-plugin#96]
### Bug description

Hello, today I can't process ACSMs. It took several tries when it finally succeed or doesn't at all.

### Operating system

Windows

### Which version of Calibre are you running?

7.12

### Which version of the ACSM Input plugin are you running?

v0.0.10

### Import type

Dragging-and-Dropping the ACSM file into the Calibre window, Using an auto-add folder (Preferences -> Adding books -> Automatic adding)

### Further information

[Calibre 18 JUn.txt](https://github.com/user-attachments/files/15880496/Calibre.18.JUn.txt)

**Comment by SeriousHornet** [comment]
I had the same issue. So here's what I did:

1. I opened the ADE I previously installed and tried to import the ACSM file there to download the EPUB file.
2. I now loaded the EPUB file into Calibre and the DeDRM plugin stripped it and gave me readable EPUB.

Then I tinkered around with the DeACSM plugin settings, 
I changed the ADE version from 2.0.1 to 3.0.1 and I again tried loading the ACSM files directly now. It worked. 
I also tried downloading books from the OverDrive Libby plugin which now gives me ACSM files, which are then converted to EPUB by DeACSM and DRM stripped off by DeDRM.

**Comment by p1nkyy** [comment]
> I had the same issue. So here's what I did:
> 
>     1. I opened the ADE I previously installed and tried to import the ACSM file there to download the EPUB file.
> 
>     2. I now loaded the EPUB file into Calibre and the DeDRM plugin stripped it and gave me readable EPUB.
> 
> 
> Then I tinkered around with the DeACSM plugin settings, I changed the ADE version from 2.0.1 to 3.0.1 and I again tried loading the ACSM files directly now. It worked. I also tried downloading books from the OverDrive Libby plugin which now gives me ACSM files, which are then converted to EPUB by DeACSM and DRM stripped off by DeDRM.

Thanks but
1. I can't get ADE working in my PC. At all. It always freeze, even when I do nothing.
2. I now mostly use Overdrive Libby and today it kept giving me unprocessed ACSM. I tried turning on & off 'Notify ACS server after fulfillment' to no avail.
3. ACSM from other vendors worked right away, on first try. Only OD acsms don't.
4. Haven't tried trying other versions of ADE version but will give it a try.

**Comment by hdp** [comment]
[This comment](https://www.mobileread.com/forums/showpost.php?s=65af7652e1edcc296b7fb493b0f8d2d1&p=4431967&postcount=449) about installing a new cert for Adobe fixed processing of Overdrive ACSM files for me without any tweaks to the DeACSM plugin settings.
